services:
  identity.db:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${IDENTITY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${IDENTITY_POSTGRES_PASSWORD}
      POSTGRES_DB: ${IDENTITY_POSTGRES_DB}
      POSTGRES_PORT: ${IDENTITY_POSTGRES_PORT}
    ports:
      - '${IDENTITY_POSTGRES_PORT:-5431}:${IDENTITY_POSTGRES_PORT:-5431}'
    volumes:
      - identity_pg_data:/var/lib/postgresql/data
  
  
  content.db:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${CONTENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CONTENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CONTENT_POSTGRES_DB}
      POSTGRES_PORT: ${CONTENT_POSTGRES_PORT}
    ports:
      - '${CONTENT_POSTGRES_PORT:-5432}:${CONTENT_POSTGRES_PORT:-5432}'
    volumes:
      - content_pg_data:/var/lib/postgresql/data

volumes:
  identity_pg_data:
  content_pg_data: