services:
  identity.db:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${IDENTITY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${IDENTITY_POSTGRES_PASSWORD}
      POSTGRES_DB: ${IDENTITY_POSTGRES_DB}
      POSTGRES_PORT: ${IDENTITY_POSTGRES_PORT}
    ports:
      - '${IDENTITY_POSTGRES_PORT:-5431}:${IDENTITY_POSTGRES_PORT:-5431}'
    volumes:
      - identity_pg_data:/var/lib/postgresql/data
  
#  identity:
#    build:
#      context: .
#      dockerfile: Infrastructure/Identity/Dockerfile
#    env_file:
#      - ./.env
#    environment:
#      - ASPNETCORE_ENVIRONMENT=${IDENTITY_ASPNETCORE_ENVIRONMENT}
#      - ASPNETCORE_URLS=http://+:${IDENTITY_ASPNETCORE_PORT}
#      - DatabaseSettings__ConnectionString=Host=${IDENTITY_POSTGRES_HOST};Port=${IDENTITY_POSTGRES_PORT};Database=${IDENTITY_POSTGRES_DB};Username=${IDENTITY_POSTGRES_USER};Password=${IDENTITY_POSTGRES_PASSWORD}
#    ports:
#      - "${IDENTITY_ASPNETCORE_PORT}:${IDENTITY_ASPNETCORE_PORT}"
#    depends_on:
#      - identity.db
  
  content.db:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${CONTENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CONTENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CONTENT_POSTGRES_DB}
      POSTGRES_PORT: ${CONTENT_POSTGRES_PORT}
    ports:
      - '${CONTENT_POSTGRES_PORT:-5432}:${CONTENT_POSTGRES_PORT:-5432}'
    volumes:
      - content_pg_data:/var/lib/postgresql/data

volumes:
  identity_pg_data:
  content_pg_data: